### ISSUE TITLE
Compatibiliy with moonfabric's trinkets, notably, the —> pain box

### ISSUE THREAD

**Issue by Aesthir** [wisp-forest/accessories#124]
The [moonfabric](https://modrinth.com/mod/moonfabric) mod contains a number of [trinkets](https://modrinth.com/mod/moonfabric/gallery). None of the trinkets the player was wearing are kept on the player between logins. Instead, when the player logs back into a server, the trinkets are placed in the player's inventory (or scattered about if there is no rooom). Workaround is to keep inventory free and re-eqiup them every time.

One trinket in particular poses a larger issue... the **_pain box_**. This trinket increases the number of belt slots and back slots. When relogging in, it simply disappears completely, along with every other trinket that was placed in every belt and back slot (including the original back slot). This leads to entire vanishing entire backpacks along with their contents. Strangely enough, the backpack ([travelersbackpack](https://modrinth.com/mod/travelersbackpack) in my case) can still be accessed through [cardinal components](https://modrinth.com/mod/cardinal-components-api) hotkey assignment, at least until you put on another backpack, then it's wiped. It also gets wiped upon death.

The trinkets are saved properly upon quitting the game, as they appear in the playerdata.dat file. They all get unequipped, or destroyed only when logging back into the game on a later date.

Thanks!

**Comment by Noaaan** [comment]
What version of Accessories are you using? We recently recieved a similar issue, which was fixed today with the latest release of Accessories (beta 40). Could you try out this new version and see if it solves your issue?

**Comment by Aesthir** [comment]
Unfortunately, I can not try beta 40 because my server is running a MC 1.21. At the time of writing, I was using the most recent Accessories release on Modrinth, beta 35+1.21. I'd be happy to try out the new version as soon as you publish it for 1.21, though. :^)

**Comment by Dragon-Seeker** [comment]
@Aesthir Try the latest 1.1.0 version as the fix should be contained within there

**Comment by Aesthir** [comment]
okay, I just tried it. Both the client and the server (both running Minecraft v1.21) won't even start up due to Accessories v1.10-beta.4+1.21.1. I read through the crash report and managed to figure out the problem, which I solved with a little ingenuity. I don't think most people will be able to solve the problem, though, so the game is disabled for them once they upgrade to the newest version of Accessories.

Problem: the Trinkets Compat Layer for Accessories needs to be updated to beta.14 to work with the new release of Accessories, but the new version isn't offered for Minecraft v1.21.

Work Around: install the [Trinkets Compat Layer for Accessories](https://modrinth.com/mod/accessories-tc-layer/versions) v3.10..0-beta.14 for Minecraft v1.21 and disregard the incompatibility warning.

I can play the game but every attack on a newly spawned entity gives this error:
```java
[Server thread/ERROR]: Failed to handle packet net.minecraft.class_2824@114401f9, suppressing error
java.lang.IllegalArgumentException: Parameters not allowed in this parameter set: [<parameter minecraft:damage_source>, <parameter minecraft:attacking_entity>]
	at knot/net.minecraft.class_8567$class_8568.method_51875(class_8567.java:136) ~[server-intermediary.jar:?]
	at knot/io.wispforest.accessories.api.events.extra.LootingAdjustment.lambda$static$2(LootingAdjustment.java:35) ~[accessories-fabric-1.1.0-beta.4+1.21.1.jar:?]
	at knot/io.wispforest.accessories.api.events.extra.ExtraEventHandler.lootingAdjustments(ExtraEventHandler.java:36) ~[accessories-fabric-1.1.0-beta.4+1.21.1.jar:?]
	at knot/net.minecraft.class_125.wrapOperation$zzf000$accessories$attemptAdjustCountWithAccessoriesLooting(class_125.java:528) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_125.wrapOperation$zzf000$accessories$attemptAdjustCountWithAccessoriesLooting$mixinextras$bridge$17(class_125.java) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_125.method_522(class_125.java:66) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_120.method_521(class_120.java:37) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_120.apply(class_120.java:17) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_131.method_53347(class_131.java:90) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_117.method_514(class_117.java:16) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_77.method_433(class_77.java:36) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_85$1.method_426(class_85.java:66) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_55.method_345(class_55.java:76) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_55.method_341(class_55.java:99) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_52.method_328(class_52.java:92) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_83.method_433(class_83.java:46) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_85$1.method_426(class_85.java:66) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_55.method_345(class_55.java:76) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_55.method_341(class_55.java:99) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_52.method_328(class_52.java:92) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_52.method_51880(class_52.java:101) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_16077(class_1309.java:1485) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_16077(class_1308.java:527) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_16080(class_1309.java:1434) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_6078(class_1309.java:1399) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_5643(class_1309.java:1252) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1657.method_7324(class_1657.java:1303) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3222.method_7324(class_3222.java:1743) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3244$1.method_34218(class_3244.java:1650) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2824$1.method_34213(class_2824.java:174) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2824.method_34209(class_2824.java:74) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3244.method_12062(class_3244.java:1610) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2824.method_12251(class_2824.java:61) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2824.method_11054(class_2824.java:15) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:121) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:814) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```
Would it be possible for you to create an Accessories release and TC Layer for v1.21?
---
Finally, I tested whether the moonstone trinkets stay or vanish upon server re-entry. They still vanish. :^/

**Comment by Dragon-Seeker** [comment]
@Aesthir This crash should be fixed with the latest release of Accessories and you should update your pack to 1.21.1 as that is the known good target for accessories and most case should be fine for you modpack

**Comment by Aesthir** [comment]
Okay, I spent the day upgrading the server, and all clients and mods. I am now using the latest versions of the mods (Accessories 1.1.0-beta.5+1.21.1 and Accessories TC Layer 3.10.0-beta.15+1.21.1) on the latest release of Minecraft (v1.21.1) using the latest fabric loader (0.16.7) and the latest fabric api (0.105.0+1.21.1). I logged into the server and.........

### The problem persists!
Not only do all trinkets in all backpack slots and all belt slots completely disappear, but all trinkets placed in the cosmetic slot versions of those slots also vanish upon every login.

This issue is not fixed and should not be marked as closed...

**Comment by Dragon-Seeker** [comment]
Ah, I believe I got this mixed up thinking this was the forge version of moon which was fixed but the trinkets version needed the same fix as well I believe, I can get a fix out later today for this I hope

**Comment by Dragon-Seeker** [comment]
@Aesthir Update has been pushed and it seems fixed within prod testing

**Comment by Aesthir** [comment]
Ahhh... that's the issue. I tried beta.6 release and it has fixed the issue... the trinkets are no longer vanishing. One surprise though, it's possible to cheat with this release by getting the extra trinkets slots without wearing the pain box now, which releases you from its negative effects.

I noticed beta.7 was just released. I haven't tried that one yet.

Thank you.
